Fix sign of cross track error obtained from RMB sentence
SignalK/nmea0183-signalk pull request #205
Opened 2021-09-26 19:16 UTC by ardbiesheuvel

XTE.js has this

  const direction = parts[3].trim().toUpperCase() === 'L' ? 1 : -1

signalk-to-nmea0183/sentences/RMB.js has this

      return nmea.toSentence([
        '$IIRMB',
        crossTrackError.toFixed(2),
        crossTrackError < 0 ? 'R' : 'L',
        ...

RMB.js does the opposite, and produces a negative value when the required
correction is to steer left. The definition in XTE.js appears to produce the
expected result in combination with my autopiot and the NMEA2000 conversions
as well, so let's change RMB.js to match XTE.js

Signed-off-by: Ard Biesheuvel <ardb@kernel.org>

2021-09-27 18:29 UTC, tkurki requested changes
Nice!

You need to change the checksum in the test input sentences.

2021-09-27 20:10 UTC, ardbiesheuvel commented
> Nice!
> 
> You need to change the checksum in the test input sentences.

Ah yes, of course. Will fix and resubmit

2021-09-30 18:07 UTC, tkurki approved these changes

2021-09-30 18:08 UTC, merged

2021-09-30 18:10 UTC, tkurki commented
Published in 3.10.2. Thank you!